---
- name: Copy /etc/apt/sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    mode: 0644

- name: Refresh APT cache and update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: True
